version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopasswd
    networks:
      - mongo-network

  go-fiber-hrms:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - mongo-network
    restart: always

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopasswd
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongo
    networks:
      - mongo-network
    restart: always

volumes:
  mongo_data:

networks:
  mongo-network:
